apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    app: db-pv
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /run/desktop/mnt/host/c/K8sDb

# /run/desktop/mnt/host/c equivalente ao c: pra quem usa windows